# Generated by Django 4.0.3 on 2022-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('citizenship', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('meternum', models.CharField(default=None, max_length=200, unique=True)),
                ('previousunit', models.IntegerField(default=0)),
                ('currentunit', models.IntegerField(default=0)),
                ('discountamount', models.IntegerField(default=0)),
                ('fineamount', models.IntegerField(default=0)),
                ('totaldue', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('citizenship', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
