# Generated by Django 4.0.4 on 2022-05-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rates_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='latestunitdue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customers',
            name='previousdue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customers',
            name='totaldue',
            field=models.IntegerField(default=0),
        ),
    ]
