# Generated by Django 4.0.4 on 2022-05-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customers_latestunitdue_customers_previousdue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='latestunitdue',
        ),
    ]
