# Generated by Django 4.0.4 on 2022-05-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customers_latestunitdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='previousdue',
        ),
    ]
