# Generated by Django 4.0.4 on 2022-05-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customers_currentunit_customers_discountamount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='meterno',
        ),
        migrations.AddField(
            model_name='customers',
            name='meternum',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
